"""Adiciona daily_plan_expiration à tabela user

Revision ID: 62d4e7e9af55
Revises: c6af9db09aa0
Create Date: 2025-03-11 11:02:45.177161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d4e7e9af55'
down_revision = 'c6af9db09aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_plan_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_plan_expiration')

    # ### end Alembic commands ###
